# Generated by Django 4.0.1 on 2022-01-25 14:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('student_school', '0002_alter_student_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registration_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
